spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/ishare_kh
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: true


# spring:
#      thymeleaf:
#        cache: false
#        prefix: classpath:/templates
server:
  port: 8080
zuul:
  routes:
    foos:
      path: /authors/**
      url: https://newiosapi.herokuapp.com/rest/authors

